name: 'build-excel-addin'
description: 'Build an excel addin from VBA source files.'
author: 'Kevin Nowaczyk'
branding:
  icon: settings
  color: black
inputs:
  path:
    description: 'The path to the source files.'
    default: 'src'
  file_name:
    description: 'The name of the final addin.'
    default: 'Addin.xlam'
runs:
  using: "composite"
  steps:
    - run: |
        python -m pip install git+https://github.com/Beakerboy/vbaProject-Compiler@dev#egg=vbaproject_compiler
        python -m pip install git+https://github.com/Beakerboy/MS-CFB@dev#egg=ms_cfb
        python -m pip install git+https://github.com/Beakerboy/Excel-Addin-Generator@File-hash
      shell: bash
    - run: |
        python -m vbaproject_compiler ${{ inputs.path }} ./project
      shell: bash
